language: node_js
node_js:
  - 15

cache:
  yarn: true
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - yarn install
  - yarn build

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target_branch: gh-pages
  local_dir: public
  on:
    branch: master
